### ISSUE TITLE
本地部署+v2ray代理，服务端"all sources are down"错误

### ISSUE THREAD

**Issue by zybzyb521** [TheodoreKrypton/JavPy#85]
在本地部署，环境python3.8+chrome，
用v2ray开代理，config里加了代理配置："proxy": "sock5://127.0.0.1:10808",
浏览器点击new，是下面的错误，看起来像是：

    Awesome! Now try to type
        JavPy.serve()
    and open http://localhost:8081 to enjoy driving!

    If you want to run a telegram bot server, instead, please type
        JavPy.serve_tg(token)
    But please get a token from the bot father first

    More info: https://github.com/theodorekrypton/JavPy

 * Serving Flask app "JavPy.app.webserver.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Feb/2020 11:39:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /search/video HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /css/chunk-vendors.728eb7d9.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /css/app.3b1f7acb.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /js/app.4c5df64c.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /js/chunk-vendors.592b69e7.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /fonts/element-icons.535877f5.woff HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:39:59] "GET /img/logo.7906e173.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2020 11:40:00] "GET /favicon.ico HTTP/1.1" 200 -
{'page': 1, 'userpass': 'f6e3e83b839c10023138848f'}
[2020-02-19 11:40:05,673] ERROR in app: Exception on /new [POST]
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\JavPy\app\webserver\app.py", line 134, in new
    res = Functions.get_newly_released(False, params["page"])
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\JavPy\utils\common.py", line 29, in _wrapped
    res = func(*args, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\JavPy\functions\__init__.py", line 49, in get_newly_released
    return New.get_newly_released(up_to, which_page)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\JavPy\functions\new.py", line 25, in get_newly_released
    cls.newly_released[which_page] = cls.__get_newly_released_from_sources(which_page)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\JavPy\functions\new.py", line 69, in __get_newly_released_from_sources
    return cls.__find_usable_source(page)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\JavPy\functions\new.py", line 59, in __find_usable_source
    raise Exception("all sources are down")
Exception: all sources are down
127.0.0.1 - - [19/Feb/2020 11:40:05] "POST /new HTTP/1.1" 500 -

**Comment by TheodoreKrypton** [comment]
你好，因为我没有用过v2ray，能不能先看一下开了代理后浏览器能不能上https://www5.javmost.com/。还有如果浏览器能上的话，建议直接copy浏览器的http代理配置。或者是只能用socks5代理吗？

**Comment by zybzyb521** [comment]
浏览器用代理可以打开https://www5.javmost.com/的；
设置用http代理的话，也是没有内容；

服务端错误：
127.0.0.1 - - [21/Feb/2020 11:56:44] "GET / HTTP/1.1" 200 -
{'page': 1, 'userpass': '15627e5366676ee5e2d6696e'}
[2020-02-21 11:57:33,002] ERROR in app: Exception on /new [POST]
Traceback (most recent call last):
Exception: all sources are down
127.0.0.1 - - [21/Feb/2020 11:57:33] "POST /new HTTP/1.1" 500 -

过程中间代理看到访问javlibrary都是正常的；
2020/02/21 11:57:23 tcp:127.0.0.1:56679 accepted tcp:www.javlibrary.com:80 [proxy] 
2020/02/21 11:57:27 tcp:127.0.0.1:56681 accepted tcp:www.javlibrary.com:80 [proxy] 
2020/02/21 11:57:32 tcp:127.0.0.1:56683 accepted tcp:www.javlibrary.com:80 [proxy]

**Comment by 775cpu** [comment]
超过 10,000 人发生过性行为[[2]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-2)。
    它从泡沫的高度开始就一直活跃[[3]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-luvmen-3)。
    当他在前一份工作中担任[主持人](https://ja-m-wikipedia-org.translate.goog/wiki/%E3%83%9B%E3%82%B9%E3%83%88_(%E6%8E%A5%E5%AE%A2%E6%A5%AD)?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp)时，他在租下[芝浦](https://ja-m-wikipedia-org.translate.goog/wiki/%E8%8A%9D%E6%B5%A6?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp)一家酒吧的派对上结识了[泽木和也，并决定在](https://ja-m-wikipedia-org.translate.goog/wiki/%E6%B2%A2%E6%9C%A8%E5%92%8C%E4%B9%9F?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp)[泽木和](https://ja-m-wikipedia-org.translate.goog/wiki/%E5%89%A3%E5%B4%8E%E9%80%B2?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp)也的晚餐俱乐部帮忙。 [[3]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-luvmen-3)。
    首次登场作品是逆接，保证金10000日元[[3]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-luvmen-3)。
    他深受泽木和剑崎的影响，受到[仰慕](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-luvmen-3)。
    有一次，他在一个晚上与 30 个人发生性关系。[[3]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-luvmen-3)
    我正在做教授性知识的“一条大学” [[4]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-luvmen2-4)。
    1990年出道

    爱好：认识人
    最喜欢的地方：俱乐部、派对
    最喜欢的词：“爱”
    我目前的热潮：身体改造
    座右铭是AV中的演员是“Ayumu” [[5]](https://ja-m-wikipedia-org.translate.goog/wiki/%E4%B8%80%E6%9D%A1%E6%AD%A3%E9%83%BD?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=zh-CN&_x_tr_pto=wapp#cite_note-5)。
